version: 2

models:
  - name: int_product_latest_price
    description: Latest price of the products.
    columns:
      - name: product_name
        description: Name of the product
      - name: product_link
        description: The link of the product
      - name: price
        description: The price of the product
      - name: amount
        description: The amount of the product
      - name: snapshot_sha
        description: The SHA used to retrieve the data
      - name: snapshot_at
        description: Timestamp the snapshot data has been made