version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: pg_bonuschef
    ports:
      - "5455:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bonuschef
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
